"""MAGI-BUS vNext — software backplane.

Constructing :class:`Bus` starts Firmware with it. BaseBook fields live on the
record types (see :class:`Message`). Workers receive an identity-bound
:class:`BusForWorker` and never access BaseBooks directly.
"""

from .base.BaseBook import BaseRecord
from .base.BaseJob import BaseJob, BaseJobBoard, BaseJobResult, JobStatus
from .base.dock import AndDock, OrDock
from .base.engine import EngineFactory, PostgresBackend, SQLiteBackend
from .base.errors import (
    BackendError,
    BookNotFoundError,
    BusError,
    InvalidJobError,
    InvalidJobStateError,
    JobNotFoundError,
)
from .base.file import FileBackend
from .base.heartbeat import Slot
from .bus import Bus
from .bus_for_worker import BusForWorker, JobBoardClient
from .firmware import (
    AppendMessageJob,
    AppendMessageResult,
    ArchiveMessagesJob,
    ArchiveMessagesResult,
    CallLLMJob,
    CallLLMResult,
    ChangeProviderJob,
    ChangeProviderResult,
    Contact,
    ContactNote,
    ContactRole,
    Conversation,
    CreateContactJob,
    CreateContactNoteJob,
    CreateContactNoteResult,
    CreateContactResult,
    CreateConversationJob,
    CreateConversationResult,
    DeleteContactJob,
    DeleteContactNoteJob,
    DeleteContactNoteResult,
    DeleteContactResult,
    DeleteSettingJob,
    DeleteSettingResult,
    GetContactJob,
    GetContactNoteJob,
    GetContactNoteResult,
    GetContactResult,
    GetSettingJob,
    GetSettingResult,
    ListContactNotesJob,
    ListContactNotesResult,
    ListContactsJob,
    ListContactsResult,
    ListConversationMessagesJob,
    ListConversationMessagesResult,
    ListSettingsJob,
    ListSettingsResult,
    LLMErrorCode,
    Message,
    MessageRole,
    NoteKind,
    RecordTokenUsageJob,
    RecordTokenUsageResult,
    SetSettingJob,
    SetSettingResult,
    Setting,
    TokenUsage,
    TouchContactJob,
    TouchContactResult,
    UpdateContactJob,
    UpdateContactNoteJob,
    UpdateContactNoteResult,
    UpdateContactResult,
    UpdateConversationSummaryJob,
    UpdateConversationSummaryResult,
)

__all__ = [
    "BackendError",
    "BookNotFoundError",
    "BaseRecord",
    "Bus",
    "BusError",
    "EngineFactory",
    "FileBackend",
    "InvalidJobError",
    "InvalidJobStateError",
    "BaseJob",
    "BaseJobResult",
    "BaseJobBoard",
    "JobNotFoundError",
    "JobStatus",
    "OrDock",
    "AndDock",
    "Slot",
    "BusForWorker",
    "JobBoardClient",
    "Conversation",
    "Contact",
    "ContactNote",
    "ContactRole",
    "CreateContactJob",
    "CreateContactResult",
    "CreateContactNoteJob",
    "CreateContactNoteResult",
    "DeleteContactJob",
    "DeleteContactResult",
    "DeleteContactNoteJob",
    "DeleteContactNoteResult",
    "GetContactJob",
    "GetContactResult",
    "GetContactNoteJob",
    "GetContactNoteResult",
    "ListContactNotesJob",
    "ListContactNotesResult",
    "ListContactsJob",
    "ListContactsResult",
    "CallLLMJob",
    "CallLLMResult",
    "ChangeProviderJob",
    "ChangeProviderResult",
    "Message",
    "MessageRole",
    "NoteKind",
    "TouchContactJob",
    "TouchContactResult",
    "UpdateContactJob",
    "UpdateContactResult",
    "UpdateContactNoteJob",
    "UpdateContactNoteResult",
    "LLMErrorCode",
    "RecordTokenUsageJob",
    "RecordTokenUsageResult",
    "AppendMessageJob",
    "AppendMessageResult",
    "ArchiveMessagesJob",
    "ArchiveMessagesResult",
    "CreateConversationJob",
    "CreateConversationResult",
    "ListConversationMessagesJob",
    "ListConversationMessagesResult",
    "UpdateConversationSummaryJob",
    "UpdateConversationSummaryResult",
    "PostgresBackend",
    "SQLiteBackend",
    "Setting",
    "TokenUsage",
    "DeleteSettingJob",
    "DeleteSettingResult",
    "GetSettingJob",
    "GetSettingResult",
    "ListSettingsJob",
    "ListSettingsResult",
    "SetSettingJob",
    "SetSettingResult",
]
