"""Firmware shipped with BUS: concrete Books and Jobs.

Opening :class:`~bus.bus.Bus` loads this set. Callers do not mount it.
"""

from typing import Any

from ..base.BaseJob import BaseJob, BaseJobBoard
from ..base.engine import EngineFactory
from ..base.file import FileEngine
from .books.contactBook import MAGI_CONTACT_ID, SYSTEM_CONTACT_ID, Contact, ContactRole
from .books.contactNoteBook import ContactNote, NoteKind
from .books.conversationBook import Conversation
from .books.memoryBook import Memory, MemoryKind
from .books.messageBook import Message
from .books.promptsBook import PromptsBook
from .books.settingsBook import Setting
from .books.skillsBook import Skill, SkillsBook
from .books.taskBook import Task, TaskBook, TaskSource
from .books.toolsBook import Tool
from .jobs import (
    ArchiveMessagesJob,
    ArchiveMessagesJobBoard,
    ArchiveMessagesResult,
    CallLLMJob,
    CallLLMJobBoard,
    CallLLMResult,
    ChangeProviderNotify,
    ChangeProviderNotifyBoard,
    ChangeProviderNotifyResult,
    ChatNotify,
    ChatNotifyBoard,
    ChatNotifyResult,
    CreateContactJob,
    CreateContactJobBoard,
    CreateContactNoteJob,
    CreateContactNoteJobBoard,
    CreateContactNoteResult,
    CreateContactResult,
    CreateConversationJob,
    CreateConversationJobBoard,
    CreateConversationResult,
    CreateMemoryJob,
    CreateMemoryJobBoard,
    CreateMemoryResult,
    DeleteContactJob,
    DeleteContactJobBoard,
    DeleteContactNoteJob,
    DeleteContactNoteJobBoard,
    DeleteContactNoteResult,
    DeleteContactResult,
    DeleteMemoryJob,
    DeleteMemoryJobBoard,
    DeleteMemoryResult,
    DeleteSettingJob,
    DeleteSettingJobBoard,
    DeleteSettingResult,
    DeleteToolJob,
    DeleteToolJobBoard,
    DeleteToolResult,
    DeliveryNotify,
    DeliveryNotifyBoard,
    DeliveryNotifyResult,
    GetContactJob,
    GetContactJobBoard,
    GetContactNoteJob,
    GetContactNoteJobBoard,
    GetContactNoteResult,
    GetContactResult,
    GetConversationJob,
    GetConversationJobBoard,
    GetConversationResult,
    GetMemoryJob,
    GetMemoryJobBoard,
    GetMemoryResult,
    GetPromptJob,
    GetPromptJobBoard,
    GetPromptResult,
    GetSettingJob,
    GetSettingJobBoard,
    GetSettingResult,
    GetSkillJob,
    GetSkillJobBoard,
    GetSkillResult,
    GetTaskJob,
    GetTaskJobBoard,
    GetTaskResult,
    GetToolJob,
    GetToolJobBoard,
    GetToolResult,
    ListContactNotesJob,
    ListContactNotesJobBoard,
    ListContactNotesResult,
    ListContactsJob,
    ListContactsJobBoard,
    ListContactsResult,
    ListConversationMessagesJob,
    ListConversationMessagesJobBoard,
    ListConversationMessagesResult,
    ListMemoriesJob,
    ListMemoriesJobBoard,
    ListMemoriesResult,
    ListSettingsJob,
    ListSettingsJobBoard,
    ListSettingsResult,
    ListSkillsJob,
    ListSkillsJobBoard,
    ListSkillsResult,
    ListTasksJob,
    ListTasksJobBoard,
    ListTasksResult,
    ListToolsJob,
    ListToolsJobBoard,
    ListToolsResult,
    LLMMessage,
    LLMMessageRole,
    LLMThinkingBlock,
    LLMTool,
    LLMToolCall,
    RegisterPromptJob,
    RegisterPromptJobBoard,
    RegisterPromptResult,
    ResetPromptJob,
    ResetPromptJobBoard,
    ResetPromptResult,
    RunTaskNotify,
    RunTaskNotifyBoard,
    RunTaskNotifyResult,
    RunToolJob,
    RunToolJobBoard,
    RunToolResult,
    SetPromptJob,
    SetPromptJobBoard,
    SetPromptResult,
    SetSettingJob,
    SetSettingJobBoard,
    SetSettingResult,
    SetToolsJob,
    SetToolsJobBoard,
    SetToolsResult,
    TouchContactJob,
    TouchContactJobBoard,
    TouchContactResult,
    UpdateContactJob,
    UpdateContactJobBoard,
    UpdateContactNoteJob,
    UpdateContactNoteJobBoard,
    UpdateContactNoteResult,
    UpdateContactResult,
    UpdateConversationSummaryJob,
    UpdateConversationSummaryJobBoard,
    UpdateConversationSummaryResult,
    UpdateMemoryJob,
    UpdateMemoryJobBoard,
    UpdateMemoryResult,
)
from .versions import __version__


def create_job_boards(
    factory: EngineFactory,
    *,
    memories: EngineFactory,
    files: FileEngine,
) -> dict[type[BaseJob], BaseJobBoard[Any, Any, Any]]:
    """Create the fixed Board set shipped by Firmware."""
    from .books.contactBook import ContactBook
    from .books.contactNoteBook import ContactNoteBook
    from .books.conversationBook import ConversationBook
    from .books.memoryBook import MemoryBook
    from .books.messageBook import MessageBook
    from .books.settingsBook import SettingsBook
    from .books.toolsBook import ToolsBook

    contacts = ContactBook(memories)
    contact_notes = ContactNoteBook(memories)
    conversations = ConversationBook(memories)
    memories_book = MemoryBook(memories)
    messages = MessageBook(memories)
    settings = SettingsBook(memories)
    tasks = TaskBook(memories)
    tools = ToolsBook(memories)
    prompts = PromptsBook(files)
    skills = SkillsBook(files)
    return {
        CreateConversationJob: CreateConversationJobBoard(factory, book=conversations),
        GetConversationJob: GetConversationJobBoard(factory, book=conversations),
        ListConversationMessagesJob: ListConversationMessagesJobBoard(factory, book=messages),
        ArchiveMessagesJob: ArchiveMessagesJobBoard(factory, book=messages),
        UpdateConversationSummaryJob: UpdateConversationSummaryJobBoard(
            factory, book=conversations
        ),
        GetPromptJob: GetPromptJobBoard(factory, prompts=prompts),
        SetPromptJob: SetPromptJobBoard(factory, prompts=prompts),
        RegisterPromptJob: RegisterPromptJobBoard(factory, prompts=prompts),
        ResetPromptJob: ResetPromptJobBoard(factory, prompts=prompts),
        GetSettingJob: GetSettingJobBoard(factory, book=settings),
        SetSettingJob: SetSettingJobBoard(factory, book=settings),
        DeleteSettingJob: DeleteSettingJobBoard(factory, book=settings),
        ListSettingsJob: ListSettingsJobBoard(factory, book=settings),
        GetToolJob: GetToolJobBoard(factory, book=tools),
        SetToolsJob: SetToolsJobBoard(factory, book=tools),
        DeleteToolJob: DeleteToolJobBoard(factory, book=tools),
        ListToolsJob: ListToolsJobBoard(factory, book=tools),
        GetSkillJob: GetSkillJobBoard(factory, skills=skills),
        ListSkillsJob: ListSkillsJobBoard(factory, skills=skills),
        CallLLMJob: CallLLMJobBoard(factory),
        ChatNotify: ChatNotifyBoard(factory, book=messages),
        DeliveryNotify: DeliveryNotifyBoard(factory, book=messages),
        RunTaskNotify: RunTaskNotifyBoard(factory, book=tasks),
        GetTaskJob: GetTaskJobBoard(factory, book=tasks),
        ListTasksJob: ListTasksJobBoard(factory, book=tasks),
        RunToolJob: RunToolJobBoard(factory),
        ChangeProviderNotify: ChangeProviderNotifyBoard(factory, settings=settings),
        CreateContactJob: CreateContactJobBoard(factory, book=contacts),
        DeleteContactJob: DeleteContactJobBoard(factory, book=contacts),
        GetContactJob: GetContactJobBoard(factory, book=contacts),
        ListContactsJob: ListContactsJobBoard(factory, book=contacts),
        TouchContactJob: TouchContactJobBoard(factory, book=contacts),
        UpdateContactJob: UpdateContactJobBoard(factory, book=contacts),
        CreateContactNoteJob: CreateContactNoteJobBoard(factory, book=contact_notes),
        DeleteContactNoteJob: DeleteContactNoteJobBoard(factory, book=contact_notes),
        GetContactNoteJob: GetContactNoteJobBoard(factory, book=contact_notes),
        ListContactNotesJob: ListContactNotesJobBoard(factory, book=contact_notes),
        UpdateContactNoteJob: UpdateContactNoteJobBoard(factory, book=contact_notes),
        CreateMemoryJob: CreateMemoryJobBoard(factory, book=memories_book),
        DeleteMemoryJob: DeleteMemoryJobBoard(factory, book=memories_book),
        GetMemoryJob: GetMemoryJobBoard(factory, book=memories_book),
        ListMemoriesJob: ListMemoriesJobBoard(factory, book=memories_book),
        UpdateMemoryJob: UpdateMemoryJobBoard(factory, book=memories_book),
    }


__all__ = [
    "__version__",
    "Conversation",
    "Contact",
    "ContactRole",
    "MAGI_CONTACT_ID",
    "SYSTEM_CONTACT_ID",
    "ContactNote",
    "NoteKind",
    "Memory",
    "MemoryKind",
    "Message",
    "Setting",
    "Skill",
    "Task",
    "TaskSource",
    "Tool",
    "ArchiveMessagesJob",
    "ArchiveMessagesJobBoard",
    "ArchiveMessagesResult",
    "CreateConversationJob",
    "CreateConversationJobBoard",
    "CreateConversationResult",
    "GetConversationJob",
    "GetConversationJobBoard",
    "GetConversationResult",
    "ListConversationMessagesJob",
    "ListConversationMessagesJobBoard",
    "ListConversationMessagesResult",
    "UpdateConversationSummaryJob",
    "UpdateConversationSummaryJobBoard",
    "UpdateConversationSummaryResult",
    "GetPromptJob",
    "GetPromptJobBoard",
    "GetPromptResult",
    "RegisterPromptJob",
    "RegisterPromptJobBoard",
    "RegisterPromptResult",
    "ResetPromptJob",
    "ResetPromptJobBoard",
    "ResetPromptResult",
    "SetPromptJob",
    "SetPromptJobBoard",
    "SetPromptResult",
    "DeleteSettingJob",
    "DeleteSettingJobBoard",
    "DeleteSettingResult",
    "GetSettingJob",
    "GetSettingJobBoard",
    "GetSettingResult",
    "ListSettingsJob",
    "ListSettingsJobBoard",
    "ListSettingsResult",
    "SetSettingJob",
    "SetSettingJobBoard",
    "SetSettingResult",
    "GetSkillJob",
    "GetSkillJobBoard",
    "GetSkillResult",
    "ListSkillsJob",
    "ListSkillsJobBoard",
    "ListSkillsResult",
    "CallLLMJob",
    "CallLLMJobBoard",
    "CallLLMResult",
    "LLMMessage",
    "LLMMessageRole",
    "LLMThinkingBlock",
    "LLMTool",
    "LLMToolCall",
    "ChatNotify",
    "ChatNotifyBoard",
    "ChatNotifyResult",
    "DeliveryNotify",
    "DeliveryNotifyBoard",
    "DeliveryNotifyResult",
    "RunTaskNotify",
    "RunTaskNotifyBoard",
    "RunTaskNotifyResult",
    "GetTaskJob",
    "GetTaskJobBoard",
    "GetTaskResult",
    "ListTasksJob",
    "ListTasksJobBoard",
    "ListTasksResult",
    "RunToolJob",
    "RunToolJobBoard",
    "RunToolResult",
    "DeleteToolJob",
    "DeleteToolJobBoard",
    "DeleteToolResult",
    "GetToolJob",
    "GetToolJobBoard",
    "GetToolResult",
    "ListToolsJob",
    "ListToolsJobBoard",
    "ListToolsResult",
    "SetToolsJob",
    "SetToolsJobBoard",
    "SetToolsResult",
    "ChangeProviderNotify",
    "ChangeProviderNotifyBoard",
    "ChangeProviderNotifyResult",
    "CreateContactJob",
    "CreateContactJobBoard",
    "CreateContactResult",
    "DeleteContactJob",
    "DeleteContactJobBoard",
    "DeleteContactResult",
    "GetContactJob",
    "GetContactJobBoard",
    "GetContactResult",
    "ListContactsJob",
    "ListContactsJobBoard",
    "ListContactsResult",
    "TouchContactJob",
    "TouchContactJobBoard",
    "TouchContactResult",
    "UpdateContactJob",
    "UpdateContactJobBoard",
    "UpdateContactResult",
    "CreateContactNoteJob",
    "CreateContactNoteJobBoard",
    "CreateContactNoteResult",
    "DeleteContactNoteJob",
    "DeleteContactNoteJobBoard",
    "DeleteContactNoteResult",
    "GetContactNoteJob",
    "GetContactNoteJobBoard",
    "GetContactNoteResult",
    "ListContactNotesJob",
    "ListContactNotesJobBoard",
    "ListContactNotesResult",
    "UpdateContactNoteJob",
    "UpdateContactNoteJobBoard",
    "UpdateContactNoteResult",
    "CreateMemoryJob",
    "CreateMemoryJobBoard",
    "CreateMemoryResult",
    "DeleteMemoryJob",
    "DeleteMemoryJobBoard",
    "DeleteMemoryResult",
    "GetMemoryJob",
    "GetMemoryJobBoard",
    "GetMemoryResult",
    "ListMemoriesJob",
    "ListMemoriesJobBoard",
    "ListMemoriesResult",
    "UpdateMemoryJob",
    "UpdateMemoryJobBoard",
    "UpdateMemoryResult",
]
