import { useEffect, useState } from "react";
import ConsoleCard from "../../components/ConsoleCard";
import type { MagisRow } from "../../lib/queries";

type Role = { id: number; name: string; instruction: string; is_reserved: boolean };
type Membership = { id: number; magi_id: number; magi_name: string | null; role_id: number; role_name: string };

export function SocietyControls({ society, onChanged }: { society: MagisRow; onChanged: () => void }) {
  const [team, setTeam] = useState(society.instruction); const [roles, setRoles] = useState<Role[]>([]); const [members, setMembers] = useState<Membership[]>([]);
  const [newRole, setNewRole] = useState({ name: "", instruction: "" }); const [error, setError] = useState<string | null>(null);
  const api = async (path: string, method = "GET", body?: unknown) => { const r = await fetch(path, { method, credentials: "include", headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); if (!r.ok) throw new Error(`${r.status} ${await r.text()}`); return r.status === 204 ? null : r.json(); };
  const load = async () => { try { const [r, m] = await Promise.all([api(`/api/magis/${society.id}/roles`), api(`/api/magis/${society.id}/memberships`)]); setRoles(r as Role[]); setMembers(m as Membership[]); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { setTeam(society.instruction); void load(); }, [society.id, society.instruction]);
  const saveTeam = async () => { try { await api(`/api/magis/${society.id}`, "PATCH", { instruction: team }); onChanged(); } catch (e) { setError((e as Error).message); } };
  const createRole = async () => { try { await api(`/api/magis/${society.id}/roles`, "POST", newRole); setNewRole({ name: "", instruction: "" }); await load(); } catch (e) { setError((e as Error).message); } };
  return <ConsoleCard title={`Manage ${society.name}`}><p className="text-xs text-ink-soft mb-3">Reserved Adam and EVA roles are fixed. Create a MAGI from the MAGI panel; its membership is established at creation.</p>{error && <p className="form-error mb-3">{error}</p>}<label className="form-label">Team instruction</label><textarea className="form-input w-full min-h-28" value={team} onChange={(e) => setTeam(e.target.value)} maxLength={12000}/><button className="btn btn-primary mt-2" onClick={() => void saveTeam()}>Save team instruction</button><div className="grid lg:grid-cols-2 gap-5 mt-6"><section><h3 className="font-medium mb-2">Roles</h3>{roles.map((r) => <div className="border-t border-border py-2" key={r.id}><div className="flex justify-between"><strong>{r.name}</strong>{r.is_reserved ? <span className="text-xs text-ink-soft">Reserved</span> : <button className="text-xs text-danger" onClick={() => void api(`/api/magis/${society.id}/roles/${r.id}`, "DELETE").then(load)}>Delete</button>}</div><p className="text-xs text-ink-soft whitespace-pre-wrap">{r.instruction}</p></div>)}<input className="form-input mt-2 w-full" placeholder="New role name" value={newRole.name} onChange={(e) => setNewRole({ ...newRole, name: e.target.value })}/><textarea className="form-input mt-2 w-full" placeholder="Role instruction" value={newRole.instruction} onChange={(e) => setNewRole({ ...newRole, instruction: e.target.value })}/><button className="btn btn-secondary mt-2" disabled={!newRole.name} onClick={() => void createRole()}>Add role</button></section><section><h3 className="font-medium mb-2">Members</h3>{members.map((m) => <div className="border-t border-border py-2 flex justify-between" key={m.id}><span>{m.magi_name || `#${m.magi_id}`} <span className="text-ink-soft">— {m.role_name}</span></span><button className="text-xs text-danger" onClick={() => void api(`/api/magis/${society.id}/memberships/${m.id}`, "DELETE").then(async () => { await load(); onChanged(); })}>Remove</button></div>)}</section></div></ConsoleCard>;
}
