"""Firmware shipped with BUS: concrete Books and Jobs.

Opening :class:`~magi.new_bus.bus.Bus` loads this set. Callers do not mount it.
"""

from typing import Any

from ..base.BaseJob import BaseJob, BaseJobBoard
from ..base.engine import EngineFactory
from ..base.heartbeat import Heartbeat
from .books.contactBook import Contact, ContactRole
from .books.contactNoteBook import ContactNote, NoteKind
from .books.conversationBook import Conversation
from .books.convMembersBook import ConvMember
from .books.messageBook import Message, MessageRole
from .books.settingsBook import Setting
from .books.taskBook import Task, TaskRunStatus, TaskSource
from .books.taskRunBook import TaskRun
from .books.tokenUsageBook import TokenUsage
from .jobs import (
    AddConversationMemberJob,
    AddConversationMemberJobBoard,
    AddConversationMemberResult,
    AppendMessageJob,
    AppendMessageJobBoard,
    AppendMessageResult,
    ArchiveMessagesJob,
    ArchiveMessagesJobBoard,
    ArchiveMessagesResult,
    CallLLMJob,
    CallLLMJobBoard,
    CallLLMResult,
    ChangeProviderJob,
    ChangeProviderJobBoard,
    ChangeProviderResult,
    CreateContactJob,
    CreateContactJobBoard,
    CreateContactNoteJob,
    CreateContactNoteJobBoard,
    CreateContactNoteResult,
    CreateContactResult,
    CreateConversationJob,
    CreateConversationJobBoard,
    CreateConversationResult,
    DeleteContactJob,
    DeleteContactJobBoard,
    DeleteContactNoteJob,
    DeleteContactNoteJobBoard,
    DeleteContactNoteResult,
    DeleteContactResult,
    DeleteSettingJob,
    DeleteSettingJobBoard,
    DeleteSettingResult,
    GetContactJob,
    GetContactJobBoard,
    GetContactNoteJob,
    GetContactNoteJobBoard,
    GetContactNoteResult,
    GetContactResult,
    GetSettingJob,
    GetSettingJobBoard,
    GetSettingResult,
    ListContactNotesJob,
    ListContactNotesJobBoard,
    ListContactNotesResult,
    ListContactsJob,
    ListContactsJobBoard,
    ListContactsResult,
    ListConversationMembersJob,
    ListConversationMembersJobBoard,
    ListConversationMembersResult,
    ListConversationMessagesJob,
    ListConversationMessagesJobBoard,
    ListConversationMessagesResult,
    ListSettingsJob,
    ListSettingsJobBoard,
    ListSettingsResult,
    LLMErrorCode,
    RecordTokenUsageJob,
    RecordTokenUsageJobBoard,
    RecordTokenUsageResult,
    RemoveConversationMemberJob,
    RemoveConversationMemberJobBoard,
    RemoveConversationMemberResult,
    SetSettingJob,
    SetSettingJobBoard,
    SetSettingResult,
    TouchContactJob,
    TouchContactJobBoard,
    TouchContactResult,
    UpdateContactJob,
    UpdateContactJobBoard,
    UpdateContactNoteJob,
    UpdateContactNoteJobBoard,
    UpdateContactNoteResult,
    UpdateContactResult,
    UpdateConversationSummaryJob,
    UpdateConversationSummaryJobBoard,
    UpdateConversationSummaryResult,
)


def create_job_boards(
    factory: EngineFactory, heartbeat: Heartbeat
) -> dict[type[BaseJob], BaseJobBoard[Any, Any, Any]]:
    """Create the fixed Board set shipped by Firmware."""
    return {
        CreateConversationJob: CreateConversationJobBoard(factory, heartbeat),
        AddConversationMemberJob: AddConversationMemberJobBoard(factory, heartbeat),
        ListConversationMembersJob: ListConversationMembersJobBoard(factory, heartbeat),
        RemoveConversationMemberJob: RemoveConversationMemberJobBoard(factory, heartbeat),
        AppendMessageJob: AppendMessageJobBoard(factory, heartbeat),
        ListConversationMessagesJob: ListConversationMessagesJobBoard(factory, heartbeat),
        ArchiveMessagesJob: ArchiveMessagesJobBoard(factory, heartbeat),
        UpdateConversationSummaryJob: UpdateConversationSummaryJobBoard(factory, heartbeat),
        GetSettingJob: GetSettingJobBoard(factory, heartbeat),
        SetSettingJob: SetSettingJobBoard(factory, heartbeat),
        DeleteSettingJob: DeleteSettingJobBoard(factory, heartbeat),
        ListSettingsJob: ListSettingsJobBoard(factory, heartbeat),
        CallLLMJob: CallLLMJobBoard(factory, heartbeat),
        ChangeProviderJob: ChangeProviderJobBoard(factory, heartbeat),
        CreateContactJob: CreateContactJobBoard(factory, heartbeat),
        DeleteContactJob: DeleteContactJobBoard(factory, heartbeat),
        GetContactJob: GetContactJobBoard(factory, heartbeat),
        ListContactsJob: ListContactsJobBoard(factory, heartbeat),
        TouchContactJob: TouchContactJobBoard(factory, heartbeat),
        UpdateContactJob: UpdateContactJobBoard(factory, heartbeat),
        CreateContactNoteJob: CreateContactNoteJobBoard(factory, heartbeat),
        DeleteContactNoteJob: DeleteContactNoteJobBoard(factory, heartbeat),
        GetContactNoteJob: GetContactNoteJobBoard(factory, heartbeat),
        ListContactNotesJob: ListContactNotesJobBoard(factory, heartbeat),
        UpdateContactNoteJob: UpdateContactNoteJobBoard(factory, heartbeat),
        RecordTokenUsageJob: RecordTokenUsageJobBoard(factory, heartbeat),
    }


__all__ = [
    "Conversation",
    "ConvMember",
    "Contact",
    "ContactRole",
    "ContactNote",
    "NoteKind",
    "Message",
    "MessageRole",
    "Setting",
    "Task",
    "TaskRun",
    "TaskRunStatus",
    "TaskSource",
    "TokenUsage",
    "AppendMessageJob",
    "AppendMessageJobBoard",
    "AppendMessageResult",
    "ArchiveMessagesJob",
    "ArchiveMessagesJobBoard",
    "ArchiveMessagesResult",
    "CreateConversationJob",
    "CreateConversationJobBoard",
    "CreateConversationResult",
    "AddConversationMemberJob",
    "AddConversationMemberJobBoard",
    "AddConversationMemberResult",
    "ListConversationMembersJob",
    "ListConversationMembersJobBoard",
    "ListConversationMembersResult",
    "RemoveConversationMemberJob",
    "RemoveConversationMemberJobBoard",
    "RemoveConversationMemberResult",
    "ListConversationMessagesJob",
    "ListConversationMessagesJobBoard",
    "ListConversationMessagesResult",
    "UpdateConversationSummaryJob",
    "UpdateConversationSummaryJobBoard",
    "UpdateConversationSummaryResult",
    "DeleteSettingJob",
    "DeleteSettingJobBoard",
    "DeleteSettingResult",
    "GetSettingJob",
    "GetSettingJobBoard",
    "GetSettingResult",
    "ListSettingsJob",
    "ListSettingsJobBoard",
    "ListSettingsResult",
    "SetSettingJob",
    "SetSettingJobBoard",
    "SetSettingResult",
    "CallLLMJob",
    "CallLLMJobBoard",
    "CallLLMResult",
    "ChangeProviderJob",
    "ChangeProviderJobBoard",
    "ChangeProviderResult",
    "CreateContactJob",
    "CreateContactJobBoard",
    "CreateContactResult",
    "DeleteContactJob",
    "DeleteContactJobBoard",
    "DeleteContactResult",
    "GetContactJob",
    "GetContactJobBoard",
    "GetContactResult",
    "ListContactsJob",
    "ListContactsJobBoard",
    "ListContactsResult",
    "TouchContactJob",
    "TouchContactJobBoard",
    "TouchContactResult",
    "UpdateContactJob",
    "UpdateContactJobBoard",
    "UpdateContactResult",
    "CreateContactNoteJob",
    "CreateContactNoteJobBoard",
    "CreateContactNoteResult",
    "DeleteContactNoteJob",
    "DeleteContactNoteJobBoard",
    "DeleteContactNoteResult",
    "GetContactNoteJob",
    "GetContactNoteJobBoard",
    "GetContactNoteResult",
    "ListContactNotesJob",
    "ListContactNotesJobBoard",
    "ListContactNotesResult",
    "UpdateContactNoteJob",
    "UpdateContactNoteJobBoard",
    "UpdateContactNoteResult",
    "LLMErrorCode",
    "RecordTokenUsageJob",
    "RecordTokenUsageJobBoard",
    "RecordTokenUsageResult",
]
